### ISSUE TITLE
Test passed, no merge

### ISSUE THREAD

**Issue by raoluSmile** [PasaLab/MR-Assignments#88]
(Your NJUID here)

MF1833059

(Your Task link here)

https://github.com/Alluxio/alluxio/pull/8073

(Describe Your problem briefly here)
就是几天前测试就通过了，但是迟迟没有merge，我看之前的问题，助教有回答是让at apc999,，我也at了，但是还是没有反应，这种情况怎么办啊？
(Provide necessary information, as many as you can)
本地测试通过，线上测试也通过

**Comment by newnius** [comment]
耐心等回复

**Comment by newnius** [comment]
看了一下，你改动了整个项目的文件权限。https://github.com/Alluxio/alluxio/pull/8073/files

而且bot没有分配维护者，关掉重新提交一个吧。

**Comment by raoluSmile** [comment]
助教学长，能帮我看一下我新的PR有没有维护者，有没有改动整个文件的权限呢？我自己并没有进行什么其他的操作啊

这是新提交的PR，依旧没有被merge

https://github.com/Alluxio/alluxio/pulls

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/8105/files

没什么区别
